version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest-browsers
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: .
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:63:c2:77:fe:82:48:8d:10:28:f8:ae:b7:1f:57:52"

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  lint:
    executor: default
    steps:
      - attach
      - run:
          name: Lint
          command: |
            yarn lint:js --format junit --output-file reports/eslint/results.xml
            yarn lint:style --output-file reports/stylelint/results.txt
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
      - store_artifacts:
          path: .nuxt
      - persist
  export:
    executor: default
    steps:
      - attach
      - run:
          name: Export
          command: |
            yarn export
      - store_artifacts:
          path: dist
      - persist
  lhci:
    executor: default
    steps:
      - attach
      - run:
          name: Lighthouse
          command: |
            yarn lhci --upload.target=filesystem --upload.outputDir=reports/lighthouse
      - store_artifacts:
          path: reports
  deploy:
    executor: default
    parameters:
      stage:
        type: enum
        enum: [ "none", "dev" ]
    steps:
      - attach
      - ssh_keys
      - deploy:
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            DRYRUN=
            yarn deploy -u "`git --no-pager show -s --format='%cn <%ce>' HEAD`" `[ "<< parameters.stage >>" = "none" ] && echo " -n"`


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          context: rap-tap-app
          requires:
            - setup
      - export:
          context: rap-tap-app
          requires:
            - lint
            - build
      - lhci:
          requires:
            - export
      - deploy:
          stage: none
          context: rap-tap-app
          requires:
            - export
          filters:
            branches:
              ignore: source
      - deploy:
          stage: dev
          context: rap-tap-app
          requires:
            - export
          filters:
            branches:
              only: source
