version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  system_info:
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
  restore_yarn_packages:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION_NPM }}

  save_yarn_packages:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/.cache/yarn


jobs:
  build:
    executor:
      name: default
    steps:
      - system_info
      - checkout
      - restore_yarn_packages
      - run:
          name: Setup
          command: yarn setup
      - save_yarn_packages
      - run:
          name: Build
          command: |
            yarn generate
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  deploy:
    executor:
      name: default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:63:c2:77:fe:82:48:8d:10:28:f8:ae:b7:1f:57:52"
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "CircleCI"
            git config --global user.email "contact@riotz.works"
            yarn deploy

workflows:
  build-deploy-flow:
    jobs:
      - build:
          context: rap-tap-app
          filters:
            branches:
              ignore:
                - master
      - deploy:
          context: rap-tap-app
          requires:
            - build
          filters:
            branches:
              only:
                - source
