version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: ~/workspace
  persist:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  lint:
    executor: default
    steps:
      - attach
      - run:
          name: Lint
          command: |
            yarn lint --format junit --output-file reports/eslint/results.xml
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
      - store_artifacts:
          path: dist
      - persist
  deploy:
    executor: default
    steps:
      - attach
      - add_ssh_keys:
          fingerprints:
            - "b2:63:c2:77:fe:82:48:8d:10:28:f8:ae:b7:1f:57:52"
      - deploy:
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "CircleCI"
            git config --global user.email "contact@riotz.works"
            yarn deploy


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          context: rap-tap-app
          requires:
            - setup
      - deploy:
          context: rap-tap-app
          requires:
            - build
          filters:
            branches:
              only: source
