defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup
          command: yarn setup
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            yarn generate
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:63:c2:77:fe:82:48:8d:10:28:f8:ae:b7:1f:57:52"
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "CircleCI"
            git config --global user.email "contact@riotz.works"
            yarn deploy

workflows:
  version: 2
  build-deploy-flow:
    jobs:
      - build:
          context: rap-tap-app
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - source
          context: rap-tap-app
